### ISSUE TITLE
sqlite3.OperationalError: index colour_index already exists

### ISSUE THREAD

**Issue by Konstantinusz** [samthomson/colourage#1]
I get an error message when I run db.py

```
python db.py 

Traceback (most recent call last):
  File "db.py", line 22, in <module>
    ''')
sqlite3.OperationalError: index colour_index already exists
```

**Comment by samthomson** [comment]
db.py should only be run once, to set up the database. If you've already set it up and are restarting you'll need to drop the db.

The script could be improved to check if it already exists before creating it, PR welcome :smiley: 

I'll close the issue but feel free to re-open or create a new one if you're still stuck :smiley:
